language: minimal

services:
  - docker

script:
  - docker-compose up --detach --build
  - ./.dev/docker/bin/composer_download.sh
  - ./.dev/docker/bin/composer_update.sh
  - ./.dev/docker/bin/code_fix.sh
  - ./.dev/docker/bin/run_tests.sh

notifications:
  email: false